In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore") 

In [3]:
df = pd.read_csv("homeprices.csv") 

In [4]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
x_df = df.drop(['price'],axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [7]:
y_df = df['price']
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [8]:
lr = LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [9]:
lr.predict([[5000]])

array([859554.79452055])

In [10]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [11]:
lr.coef_

array([135.78767123])

In [12]:
lr.intercept_

180616.43835616432

Pickle File

In [13]:
import pickle

In [15]:
with open("lr_model",'wb') as file:
    pickle.dump(lr,file)

In [16]:
with open("lr_model",'rb') as file:
    np = pickle.load(file)

In [17]:
np.coef_

array([135.78767123])

In [18]:
np.intercept_

180616.43835616432

In [19]:
np.predict([[5000]])

array([859554.79452055])

In [27]:
samplejson = {
    "name" : "luminar",
    "place": "kochi",
    "phone": "86254936117"
}

In [28]:
import json
json_obj = json.dumps(samplejson)

In [29]:
json_obj

'{"name": "luminar", "place": "kochi", "phone": "86254936117"}'

In [30]:
with open("samplejson",'w') as file:
    file.write(json_obj)

In [31]:
with open("samplejson",'r') as file:
    newdata = json.load(file)

In [32]:
newdata

{'name': 'luminar', 'place': 'kochi', 'phone': '86254936117'}

In [33]:
import joblib

In [35]:
joblib.dump(lr,'model_joblib_new1')

['model_joblib_new1']

In [36]:
mj = joblib.load('model_joblib_new1')

In [37]:
joblib.load('lr_model')

LinearRegression(normalize='deprecated')

In [38]:
mj.coef_

array([135.78767123])

In [39]:
mj.intercept_

180616.43835616432