In [2]:
#install python package - Numpy
# pip install numpy

In [1]:
import numpy as np

In [4]:
#myList=[1, 2, 3, 4, 5]

In [5]:
#print(myList)

[1, 2, 3, 4, 5]


In [7]:
#type(myList)

list

In [11]:
# dir(np)

In [12]:
 # help(np)

In [15]:
#arr = np.array(myList)

In [14]:
#print(arr)
#print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
# shape of the array
#arr.shape

(5,)

In [17]:
#arr.size

5

In [25]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
type(arr)

numpy.ndarray

In [26]:
arr.shape

(3, 5)

In [28]:
arr.size

15

In [31]:
# numpy array indexing

# get the first element from the following array:

my_lst1=[1,2,3,4,5]
arr = np.array(my_lst1)
arr

array([1, 2, 3, 4, 5])

In [30]:
print(arr[0])

1


In [32]:
# get the second element from the array:

print(arr[1])

2


In [34]:
# get the third element from the array:

print("third element is:", arr[2])
print("fourth element is:", arr[3])

third element is: 3
fourth element is: 4


In [35]:
# Access 2D array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [36]:
arr[1,2]

4

In [37]:
arr[0,2]

3

In [38]:
# Access the element on 2nd row 5th column:

print("5th element on 2nd row is:", arr[1,4])

5th element on 2nd row is: 6


In [47]:
valArr = np.array([[1,2,3],[4,5,6]])  # create 2D array
print("printing the variable value", valArr, "\n")
print("printing the shape", valArr.shape, "\n")
print("printing the size", valArr.size, "\n")
print("indexing 1st row 1st element", valArr[0,0], "\n")
print("indexing 1st row 2nd column", valArr[1,2], "\n")

printing the variable value [[1 2 3]
 [4 5 6]] 

printing the shape (2, 3) 

printing the size 6 

indexing 1st row 1st element 1 

indexing 1st row 2nd column 6 



In [6]:
# Negative indexing

myList=[1,2,3,4,5,6]
arr = np.array(myList)
# print(arr)

valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [7]:
valArr[1,-1]

6

In [8]:
valArr[0,-1]

3

In [13]:
valArr[0,0]

1

In [14]:
valArr[1,-2]


5

In [27]:
# Array Slicing
myList=[1,2,3,4,5,6,7,8,9,10,11]
arr = np.array(myList)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# arr[start:end]
arr[0:4]

array([1, 2, 3, 4])

In [17]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [19]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [21]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[-1:1]

array([], dtype=int32)

In [23]:
arr[-3:-1]

array([8, 9])

In [24]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
arr[::2]

array([1, 3, 5, 7, 9])

In [26]:
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [28]:
arr[1::7]

array([2, 9])

In [29]:
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [30]:
arr[1::3]

array([ 2,  5,  8, 11])

In [31]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [32]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [33]:
arr[1:,1:4]

array([[3, 4, 5],
       [7, 6, 8]])

In [34]:
arr[:,1:]

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [7, 6, 8, 9]])

In [35]:
arr[:3,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [36]:
arr[:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [37]:
arr[:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [38]:
# Arange function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [43]:
type(list(range(1,10)))

list

In [44]:
# Linspace 
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [45]:
# Numpy Data Types

arr = np.array([1,2,3,4,5])

print(arr.dtype)

int32


In [46]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr.dtype)

|S1


In [47]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [49]:
arr = np.array(['apple','banana','cherry','bananacherry'])
print(arr.dtype)

<U12


In [52]:
arr = np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [53]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [54]:
# Array Math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [55]:
print(x)
print("**")
print(y)

[[1. 2.]
 [3. 4.]]
**
[[5. 6.]
 [7. 8.]]


In [56]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [57]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [58]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [59]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [60]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [61]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [62]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [63]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [64]:
np.square(y)

array([[25., 36.],
       [49., 64.]])

In [65]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8],[9,10]], dtype=np.float64)

In [66]:
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [67]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [68]:
x

array([[1., 2.],
       [3., 4.]])

In [75]:
# Floor, Ceil, Round

x = np.array([[1.5,2.6],[3.5,4.9]], dtype=np.float64)

In [70]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [71]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [76]:
np.round(x)

array([[2., 3.],
       [4., 5.]])

In [77]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
z = np.array([[9,10],[11,12]], dtype=np.float64)

In [78]:
x*y*z

array([[ 45., 120.],
       [231., 384.]])

In [79]:
np.multiply(x,y,z)

array([[ 5., 12.],
       [21., 32.]])

In [80]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [81]:
v.dot(w)

219

In [82]:
np.dot(v,w)

219

In [83]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
x.shape

(3, 2)

In [85]:
np.sum(x)

21

In [90]:
np.sum(x,axis=0)

array([ 9, 12])

In [91]:
# axis=0/1 0: row  1:column
np.sum(x,axis=1)

array([ 3,  7, 11])

In [92]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [94]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.sum(x,axis=0)    #columnwise sum

array([12, 15, 18])

In [96]:
np.sum(x,axis=1)    #rowwise sum

array([ 6, 15, 24])

In [97]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
x.T    #Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [3]:
# Numpy Array copy vs view
arr = np.array([1,2,3,4,5])
x = arr

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(x)

[1 2 3 4 5]


In [6]:
arr[0] = 100

In [7]:
print(arr)

[100   2   3   4   5]


In [8]:
print(x)

[100   2   3   4   5]


In [9]:
x[1] = 200

In [10]:
print(x)

[100 200   3   4   5]


In [11]:
print(arr)

[100 200   3   4   5]


In [12]:
# Numpy Array copy vs view
arr = np.array([1,2,3,4,5])
x = arr.copy()

In [13]:
print(arr)

[1 2 3 4 5]


In [14]:
print(x)

[1 2 3 4 5]


In [15]:
arr[0] = 100

In [16]:
print(arr)

[100   2   3   4   5]


In [17]:
print(x)

[1 2 3 4 5]


In [18]:
x[1] = 200

In [19]:
print(x)

[  1 200   3   4   5]


In [20]:
print(arr)

[100   2   3   4   5]


In [21]:
# Numpy Array Reshaping
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr = np.arange(1,13)
arr.shape

(12,)

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [29]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
arr_new = arr.reshape(4,3)

In [31]:
arr_new      #1D------>2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
# Flattening the arrays
# 2D-------> 1D
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
# Iterating Arrays
# np.arange(1,6)
# arr = np.arange(1,7).reshape(3,2).sum(axis=0)
arr = np.arange(1,7).reshape(3,2)

In [44]:
arr

array([ 9, 12])

In [46]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [49]:
# Joining Numpy Array
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

In [51]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [55]:
# Join two 2-D Arrays along (axis=1):

arr1 = np.array(([1,2], [3,4]))

arr2 = np.array(([5,6], [7,8]))

np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])